### ISSUE TITLE
Example missing pubspec

### ISSUE THREAD

**Issue by athornz** [Mr-Pepe/stroke-order-animator#1]
Hey! Awesome work getting started on this. I'd love to give it a try but it seems the example app is missing a pubspec and can't be run.

**Comment by Mr-Pepe** [comment]
What's the error message you get? 
When I clone the repo and execute `flutter run` I get "Target file "lib/main.dart" not found". 
Simply copying the main.dart from the example folder to the lib folder worked fine.

Let me know if that helps and I'll update the docs.

**Comment by Mr-Pepe** [comment]
I updated the package, committed the main.dart to the lib folder, but moved it to the example folder when publishing to pub. That seems a bit cumbersome but this way you see it as an example on pub, but can also directly build it when cloning the repo. This is my first pub package, so I don't know what the best practice is.

**Comment by athornz** [comment]
The example folder should be an entire flutter app which depends on the package. I'd suggest recreating the package with the Flutter tool so it will create the create structure for you, and copy in your classes.

**Comment by Mr-Pepe** [comment]
Done. Thanks for the hint and feel free to give it a try.

**Comment by athornz** [comment]
Great, that looks much better. The sample app runs nicely!

Do you have plans to implement the ability to draw strokes?

**Comment by Mr-Pepe** [comment]
Good to hear!

Yes, I want to look into a quiz mode within the next two weeks or so.

**Comment by Mr-Pepe** [comment]
I haven't updated the docs yet, but I have implemented a basic quiz mode. Feel free to check it out :)

**Comment by athornz** [comment]
oh wow that's awesome, working well already!
