### ISSUE TITLE
Pressing blank space should not be counted as mistake

### ISSUE THREAD

**Issue by sqllyw** [Mr-Pepe/stroke-order-animator#10]
as the subject line, 

A sample here:
https://hanziwriter.org/docs.html
go to Integrating Quizzes
the testing character is 码,
if press blank space, it will not count as mistake

**Comment by Mr-Pepe** [comment]
What do you mean by pressing blank space? Just tapping somewhere instead of drawing a stroke?

**Comment by sqllyw** [comment]
yes, if tap, seems counted as mistake in the example, I have not yet tested it in a real device. but if user draw, then should be counted as mistake

**Comment by Mr-Pepe** [comment]
Thanks for the feedback, should work now :)

**Comment by sqllyw** [comment]
tested and works as expected, thanks!
