### ISSUE TITLE
keeping the hand writing of user made

### ISSUE THREAD

**Issue by sqllyw** [Mr-Pepe/stroke-order-animator#12]
Hi,
This is a nice to have feature, can Stroke-order-animator keep the correct paths of a user actually draw? this might be used to show to the user his actual hand writing. thanks

**Comment by Mr-Pepe** [comment]
Only the correct paths or would you also want the incorrect ones? Should the data be passed on quiz completion or on every correct/wrong stroke? I guess I would just add it to the quiz summary, so it would be passed to the onQuizCompleteCallback, but you can get the summary from the controller any time.

**Comment by sqllyw** [comment]
only the correct paths, there could be two use cases:
1) on quiz summary, the actual writing can be shown together with the outline to see how close the practice is.
2) if the correct path can be accessed while in quizzing, then user can see every real stroke he makes.

**Comment by Mr-Pepe** [comment]
I added an option that can be set with `setShowUserStroke` that keeps the correct strokes on screen. The strokes also stay visible after the quiz ends until the quiz starts again or the character gets reset. I added a button in the example app to showcase the behaviour. 

Let me know what you think :)

**Comment by sqllyw** [comment]
will check this out and get back to you soon

**Comment by sqllyw** [comment]
works as expected, thanks.
