### ISSUE TITLE
Use strokOrder instead of _strokeOrder

### ISSUE THREAD

**Issue by Aaron2464** [Mr-Pepe/stroke-order-animator#17]
Line 365 in strokeOrderAnimationController.dart file
`void setStrokeOrder(String strokeOrder) {
    final parsedJson = json.decode(_strokeOrder.replaceAll("'", '"'));
}`

Could it use strokOrder instead of _strokeOrder? Plz
`void setStrokeOrder(String strokeOrder) {
    final parsedJson = json.decode(strokeOrder.replaceAll("'", '"'));
}`

I'd like to change strokeOrder after I get data from internet.

**Comment by Mr-Pepe** [comment]
Landed in version 1.6.1 :)

**Comment by Aaron2464** [comment]
Thank you so much. :)
