### ISSUE TITLE
event after quiz?

### ISSUE THREAD

**Issue by sqllyw** [Mr-Pepe/stroke-order-animator#6]
Hi, is there a way to know user has finished the quiz and how many mistakes? thanks

**Comment by Mr-Pepe** [comment]
Not yet, but I can look into it in the next couple of days. 

Can you explain in a bit more detail what you would like to have? 

At the moment, I only count mistakes for the current stroke to know when to show a hint. I could extend that to keep track of the mistakes for all strokes during the current quiz and make that property to public, so you can access it any time.

How would you like to be notified when the quiz finishes? Passing in a callback to the controller?

**Comment by sqllyw** [comment]
a callback will do, something onComplete with summary info

**Comment by Mr-Pepe** [comment]
Give it a try and let me know what you think

**Comment by sqllyw** [comment]
Thanks, will do

**Comment by sqllyw** [comment]
tested and works as expected, thanks.

**Comment by Mr-Pepe** [comment]
Great! Thanks for the feedback
