### ISSUE TITLE
Bad state: No element

### ISSUE THREAD

**Issue by sqllyw** [Mr-Pepe/stroke-order-animator#7]
randomly got following error, any idea?
![s1](https://user-images.githubusercontent.com/29809419/84906263-42ebc080-b0e4-11ea-93b6-5e41ad686108.png)

**Comment by Mr-Pepe** [comment]
It crashes in checkStroke which is called when you complete drawing a stroke. It says that it tries to get the first element of an iterable, but that element doesn't exist. The "first" method gets called on the path of the stroke outline, the path of the median of the stroke, and the path of what you drew. One of those paths seems to be empty but it's not clear which of those calls failed. 

Can you reproduce the error?
Which character where you looking at?

**Comment by sqllyw** [comment]
looks like if I hesitate in some stroke, not finishing it, but it works even with that error, I'll observe some more to find a way to re-produce it and get back here, thanks.
